sudo: required
language: generic
services:
  - docker
git:
  submodules: false
branches:
  only:
    - master
before_install:
  - docker pull jpsim/sourcekit
script:
  - git clone https://github.com/jpsim/SourceKitten.git
  - cd SourceKitten && git checkout jp-wip-linux && swift build && swift test
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
